services:
    backend:
        build: .
        container_name: backend
        command: python manage.py runserver 0.0.0.0:8080
        volumes:
            - ./core:/app
        ports:
            - "8080:8080"
        environment:
            - SECRET_KEY=test
            - DEBUG=True
    smtp4dev:
        image: rnwood/smtp4dev:v3
        restart: always
        ports:
            - '5050:80'
        volumes:
            - smtp4dev-data:/smtp4dev
        environment:
            - ServerOptions_HostName=smtp4dev

volumes:
    smtp4dev-data:
